### ISSUE TITLE
Mod causes crash in Encore once opening Mighty and Ray's capsule

### ISSUE THREAD

**Issue by vPubneutral** [tariq-nasheed/HyperMania#10]
Using latest Mania/RDSK5 decomp, built from source, as of writing. Vulkan version, if it matters

Only mod loaded is HyperMania

Log attached: 
[log.txt](https://github.com/tariq-nasheed/HyperMania/files/14293266/log.txt)

**Comment by Briskybit** [comment]
I seem to be running into this issue as well. Here is my log file
[log.txt](https://github.com/tariq-nasheed/HyperMania/files/15449693/log.txt)

**Comment by tariq-nasheed** [comment]
Hi! sorry for the late reply, i'm just now coming off a hiatus from working on the mod.
It seems like this bug was fixed with [6afed9d](https://github.com/tariq-nasheed/HyperMania/commit/6afed9db7973008e91429d6d2f4feae348d1dad2) a couple of weeks before this issue was posted (maybe I didn't push it yet?) but I never made a release containing it until now.  Please try either downloading [the new release](https://github.com/tariq-nasheed/HyperMania/releases/tag/alpha-3) or pulling and building the new version.

**Comment by vPubneutral** [comment]
Issue no longer occurs in the latest release
