### ISSUE TITLE
Install instructions (original title: "what")

### ISSUE THREAD

**Issue by AuraofLucario991** [tariq-nasheed/HyperMania#2]
I have the game decomped, how do i install it?? the instructions arent very clear as to what to do, i need a step by step intruction.

**Comment by tariq-nasheed** [comment]
the mod's root directory (the one with mod.ini in it) is supposed to be placed in a directory in the decomp called mods/ as seen here (ignore Hyper-Sonic-ManiaDecomp and TODO as they're for development purposes)
![Screenshot_2023-08-29_16-45-09](https://github.com/tariq-nasheed/HyperMania/assets/65060738/a7157ab7-337b-4c2f-b197-d780b9c44e76)
also note that the mod contents are supposed to have their own parent directory (here it's HyperMania but you can name it whatever you want) instead of being placed in mods/ directly

**Comment by tariq-nasheed** [comment]
README now includes install instructions so i dont need to keep this issue open anymore
